--- #YAML:1.0
 name: Sakai-Stats
 abstract: Perl library for generating Sakai Statistics
 version: 0.02
 author:
   - Daniel Parry <perl@ddp.me.uk>
 license: perl
 distribution_type: module
 requires:
   Data::Dumper: 0
   DBD::mysql: 0
   DBI: 0
   Getopt::Long: 0
   Net::LDAP: 0
   Pod::Usage: 0
   Text::CSV: 0
 build_requires:
   Test: 0
 urls:
   license: http://dev.perl.org/licenses/artistic.html
